version: '3.8'

services:
  web:
    build: ./dvm_task
    command: /bin/bash -c "
                    export MIGRATE=0 &&
                    python manage.py migrate &&
                    export MIGRATE=1 &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./dvm_task:/usr/src/dvm_task/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      DATABASE: postgres
      SQL_HOST: db
      SQL_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "postgres_alpha1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mynameisansh"
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: