services:
  web:
    build:
      context: ./dvm_task
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "export MIGRATE=0 &&
        python manage.py migrate &&
        export MIGRATE=1 &&
        python manage.py collectstatic --noinput && 
        gunicorn dvm_task.wsgi:application --bind 0.0.0.0:8000",
      ]
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: "postgres_alpha1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mynameisansh"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
