name: final_yml
services:
  web:
    image: web
    build:
      context: .
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
    command: sh -c "python3 manage.py collectstatic --no-input && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
  db:
    container_name: db_container
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mynameisansh"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3