# Generated by Django 5.1.6 on 2025-02-17 10:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='BusServiceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Bus Registrations',
            },
        ),
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Bus Stops',
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.busstops')),
            ],
            options={
                'verbose_name_plural': 'Select Bus Stop',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.addbus')),
                ('stop_id', models.ManyToManyField(through='booking.BusStop', to='booking.busstops')),
            ],
            options={
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.AddField(
            model_name='busstop',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('Luxury', 'Luxury'), ('Ordinary', 'Ordinary'), ('Sleeper', 'Sleeper')], max_length=100)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.addbus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bus_stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.busstop')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.route')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='SeatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('Luxury', 'Luxury'), ('Ordinary', 'Ordinary'), ('Sleeper', 'Sleeper')], max_length=100)),
                ('seat_no', models.IntegerField()),
                ('seat_price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('seat_availability', models.BooleanField(default=True)),
                ('bus_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.busserviceregistration')),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.addbus')),
            ],
            options={
                'verbose_name_plural': 'Seat Information',
            },
        ),
        migrations.AddField(
            model_name='addbus',
            name='seat_type',
            field=models.ManyToManyField(through='booking.SeatInfo', to='booking.busserviceregistration'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wallets',
            },
        ),
    ]
