# Generated by Django 5.1.6 on 2025-02-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatinfo',
            name='seat_availability',
            field=models.BooleanField(default=True),
        ),
    ]
