# Generated by Django 5.1.6 on 2025-02-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
